### ISSUE TITLE
Install Link invalid

### ISSUE THREAD

**Issue by mgaynor1** [biotaphy/BiotaPhyPy#37]
Seems the install link ( https://biotaphy.github.io/BiotaPhyPy/sphinx/pages/installation.html) is broken. Is there a new link?

**Comment by cjgrady** [comment]
Yes, it should be https://biotaphy.github.io/BiotaPhyPy/pages/installation.html.  Where did the other link come from?

**Comment by mgaynor1** [comment]
The readme on this repository [README.md](https://github.com/biotaphy/BiotaPhyPy#readme)

**Comment by cjgrady** [comment]
Thanks, it should be updated now along with project images.
